apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-frontend
  namespace: medical-app
  labels:
    app: medical-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-frontend
  template:
    metadata:
      labels:
        app: medical-frontend
    spec:
      containers:
        - name: medical-frontend
<<<<<<< HEAD
          image: jucejara/medical-frontend:latest
          imagePullPolicy: IfNotPresent
=======
          image: medical-frontend:latest
          imagePullPolicy: Never
>>>>>>> 492a118d5c789e30b3af398d347adb27f33a0ff4
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"