server:
  port: 8080
<<<<<<< HEAD
 
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/db_medical?useSSL=false&serverTimezone=UTC
    username: root
    password: ${MYSQL_PASSWORD:netect123}
    driver-class-name: com.mysql.cj.jdbc.Driver
 
  jpa:
    hibernate:
      ddl-auto: none
=======

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/db-medical?useSSL=false&serverTimezone=UTC
    username: root
    password: ${MYSQL_PASSWORD:netect123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
>>>>>>> 492a118d5c789e30b3af398d347adb27f33a0ff4
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
<<<<<<< HEAD
 
=======

>>>>>>> 492a118d5c789e30b3af398d347adb27f33a0ff4
  sql:
    init:
      mode: always
      platform: mysql
      encoding: UTF-8
<<<<<<< HEAD
 
=======

>>>>>>> 492a118d5c789e30b3af398d347adb27f33a0ff4
springdoc:
  api-docs:
    path: /api-docs
  show-actuator: false
<<<<<<< HEAD
  packages-to-scan: com.netec.medical.controller
=======
  packages-to-scan: com.netec.medical.controller
>>>>>>> 492a118d5c789e30b3af398d347adb27f33a0ff4
